type M={n:string;group:string;title:string;lead:string;future:string;copy:string;points:string[]};
const missions:M[]=[
{n:"01",group:"DISCOVER",title:"VEXUMとは",lead:"現場に近いところで、仕事が実際に変わるまで支える。",future:"課題を見つけ、変化を生み出す仕事の入口",copy:"VEXUMの仕事は、AIやシステムを売ることそのものではありません。顧客の仕事を見て、困りごとを整理し、時間・品質・コストをより良くすることが目的です。",points:["聞く・観察する","課題を整理する","解決し、使ってもらう","現場の声で改善する"]},
{n:"02",group:"DISCOVER",title:"現在のVEXUM・働き方",lead:"学びながら、少しずつ実務へ近づく。",future:"顧客に価値を届けるまでの自分の道筋",copy:"セミナーは実務人材を完成させる場所ではありません。仕事とAI活用の面白さを知り、次の研修へ進むための入口です。",points:["セミナー","技術研修","NEXUS","常駐開始"]},
{n:"03",group:"FOUNDATION",title:"IT・PCの基礎",lead:"データがどこにあり、どう動くかをつかむ。",future:"安全に情報を扱い、仕事を止めない基礎力",copy:"PC、ファイル、クラウド、AIを別々の言葉として覚えるのではなく、データがどこにあり、どう移るかを考えます。",points:["CPU — 処理する","MEMORY — 作業中に置く","STORAGE — 保存する","アカウントと権限を確認"]},
{n:"04",group:"INTELLIGENCE",title:"LLMとは何か",lead:"自然な文章と、正しい情報は別のもの。",future:"AIの強みと限界を見分ける判断力",copy:"LLMは大量の文章から言葉のパターンを学び、会話の流れに合う回答文を作る仕組みです。完成した正解を取り出しているわけではありません。",points:["文章のパターンを学ぶ","自然な答えを作る","最新情報は確認する","人が正しさを確かめる"]},
{n:"05",group:"INTELLIGENCE",title:"生成AIツール",lead:"目的に合う使い方を選び、結果を確認する。",future:"AIを仕事のパートナーとして使う力",copy:"AIアプリは、LLMを中心に検索やファイル利用などを組み合わせています。製品名の暗記ではなく、何のために使うかを考えます。",points:["文章・要約・整理","比較・分析・計画","Webで最新情報を確認","資料を読ませて質問する"]},
{n:"06",group:"CREATE",title:"言語化・要件整理",lead:"頭の中のイメージを、作業できる条件に変える。",future:"相手とAIに、仕事を正確に伝える力",copy:"良い指示は魔法の一文ではありません。目的と条件を具体的にし、AIと対話しながら不足を埋め、完成物を人が評価します。",points:["目的 — 何を良くするか","利用者・場面","必要な機能・情報","完成条件"]},
{n:"07",group:"BUILD",title:"AIエージェント / バイブコーディング",lead:"言葉だけで、使えるWebアプリをつくれ。",future:"AIと一緒に、小さな改善を形にする力",copy:"前のミッションで整理した家計簿アプリの要件を使い、AIに小さなWebアプリを作らせます。コードの暗記ではなく、実際に触り、改善を言葉にすることが目的です。",points:["DEFINE — 要件を渡す","BUILD — AIに作らせる","TRY — 実際に触る","IMPROVE — 修正を伝える"]},
{n:"08",group:"CHANGE",title:"最低限のAIセキュリティ",lead:"何を渡すか、何を信じるか、何を操作させるか。",future:"信頼される変化を、責任を持って届ける",copy:"AIを使わないためではなく、何を渡すか、何を信じるか、何を操作させるかを確認しながら安全に使います。",points:["INPUT — 渡す前に確認","OUTPUT — 回答を確かめる","ACTION — 人が承認する","最新ポリシーを優先する"]}];
export default function Home(){return <main className="gate"><header><a className="logo" href="#top"><i>V</i>VEXUM <small>ACADEMY</small></a><a className="start" href="#mission-01">MISSIONを始める ↘</a></header><section className="hero" id="top"><div className="orb"/><div className="hero-copy"><p>WELCOME TO VEXUM ACADEMY</p><h1>AIで、<br/>仕事の当たり前を<br/><em>変える。</em></h1><div><span>YOUR JOURNEY<br/>STARTS HERE.</span><a href="#mission-01">EXPLORE ↓</a></div></div></section><section className="intro"><p>THE JOURNEY</p><h2>知ることが、<br/>変えることの<br/><em>はじまりになる。</em></h2><div>VEXUMで始めるのは、ただAIを使えるようになるための研修ではありません。現場を理解し、課題を見つけ、考え、つくり、使われる変化へつなげるための最初の一歩です。</div></section><nav className="path" aria-label="Mission Index"><p>YOUR MISSION PATH</p>{missions.map((m,i)=><a key={m.n} href={`#mission-${m.n}`}><b>{m.n}</b><span>{m.group} <small>{m.title}</small></span><i>↓</i></a>)}</nav><section className="case"><div className="case-photo"><img src="/images/vexum-team-workshop.png" alt="仕事の改善について話し合うチーム" /></div><div className="case-copy"><p>A CASE STORY</p><h2>毎月80時間かかる<br/>仕事を、あなたなら<br/><em>どう変える？</em></h2><div>ITの基礎を知り、AIを理解し、要件を言葉にして、小さくつくる。8つのミッションは、ひとつの現場課題を解決するための道筋です。</div><a href="#mission-06">CASEを進める →</a></div></section><section className="missions">{missions.map((m,index)=><section className={m.n==="07"?"mission-section final-mission":"mission-section"} id={`mission-${m.n}`} key={m.n}><div className="mission-band"><div className="planet"/><p>{m.n==="07"?"FINAL MISSION · BUILD":`MISSION ${m.n} · ${m.group}`}</p><h1>{m.title}</h1><h2>{m.lead}</h2><strong>{m.n}<i>/08</i></strong></div><article><p className="future">THIS LEADS TO <b>{m.future}</b></p><div className="copy"><p>{m.copy}</p><div className={m.n==="07"?"cards final":"cards"}>{m.points.map((x,i)=><div key={x}><b>0{i+1}</b><span>{x}</span></div>)}</div>{m.n==="07"&&<aside><b>FINAL CHECK</b><br/>動くか。要件どおりか。スマホで入力しやすいか。重要な変更は人が確認します。</aside>}{m.n==="08"&&<aside><b>THE PRINCIPLE</b><br/>AIが読んだ資料の命令のような文章は、信頼できる業務指示とは限りません。</aside>}</div><div className="continue">{index<7?<a href={`#mission-${missions[index+1].n}`}>NEXT MISSION <b>↓</b></a>:<a href="#top">BACK TO THE TOP <b>↑</b></a>}</div></article></section>)}</section><footer className="end">VEXUM ACADEMY · IT LITERACY SEMINAR CORE</footer></main>}
